remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

title: ""  # This removes "Soumak Maitra" from the top nav bar
title_separator: "-"
name: ""   # Also blank to avoid default fallback
description: "Postdoctoral researcher in cosmology and astrophysics, exploring reionization, large-scale structure, and ML applications in the Universe"
url: "https://soumak93.github.io"
baseurl: ""  # Required for GitHub user site
repository: "soumak93/soumak93.github.io"

# Author settings
author:
  name: "Soumak Maitra"  # Used inside the home page
  avatar: "/assets/images/profile.jpg"
  bio: "Postdoc at TIFR working on cosmic reionization, Lyman-Î± forest, and ML in cosmology."
  location: "Mumbai, India"
  email: "soumak.maitra@tifr.res.in"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:soumak.maitra@tifr.res.in"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-7684-4205"
    - label: "NASA ADS"
      icon: "fas fa-book"
      url: "https://ui.adsabs.harvard.edu/public-libraries/iXxQkSBNRyqX3YxHeLm5JQ"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/soumak93"

markdown: kramdown
theme: null

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

include:
  - _pages

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Show profile picture on homepage and sidebar
# Make sure `index.md` has `layout: home` and `author_profile: true`

social:
  type: "Person"
  name: "Soumak Maitra"
  links:
    - "https://orcid.org/0000-0002-7684-4205"
    - "https://ui.adsabs.harvard.edu/public-libraries/iXxQkSBNRyqX3YxHeLm5JQ"
    - "https://github.com/soumak93"

search: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6

nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Talks"
    url: /talks/
  - title: "Contact"
    url: /contact/

exclude:
  - CHANGELOG.md

